package oops;


public class Encalsulation_Set_Get 
{
    public static void main(String[] args) 
    {
        Emp Ram=new Emp();
        Ram.setSalary(5000);
        System.out.println(Ram.getSalary());
    }
}
 class Emp 
{
   private int Salary;  

    public int getSalary() // generated by right clicking->generate code->Getter and Setter
    {
        return Salary;
    }

    public void setSalary(int Salary) 
    {
        this.Salary = Salary;
    }
     
}
